GET http://localhost:3000/api/users 

###
GET http://localhost:3000/api/cohorte

###
GET http://localhost:3000/api/likes

###
GET http://localhost:3000/api/comments
###
GET http://localhost:3000/api/posts


